import * as vscode from 'vscode';
import { FileSnapshot, snapshot } from './FileSnapshot';

export class ElevateContext {
    // File snapshot with version numbers and full text before analysis
    readonly snapshot: FileSnapshot;

    // Initial inputs
    // Text from VScode of active file after sanitization
    analysisTarget?: string;

    
    // Pipeline outputs
    // File after being parsed
    //parsed?: ParsedFile;

    // Prompt generated by PromptBuilder to sender to Ollama
    // prompt?: Prompt obj;

    // Response from Ollama
    // modelResponse?: Response obj;

    // compiler error/warnings
    diagnostics?: vscode.Diagnostic[];

    constructor(doc: vscode.TextDocument) {
        this.snapshot = snapshot(doc);
    }

}
