import * as vscode from 'vscode';
import { FileSnapshot, snapshot } from '../backend/FileSnapshot';
import { BlockEvent } from './parserTypes';
import { ChatMessage, ModelAnalysisResult } from './types';

export class ElevateContext {
    // File snapshot with version numbers and full text before analysis
    readonly snapshot?: FileSnapshot;

    // Explit version tracking
    readonly version?: number;
    
    // For testing
    text?: string;

    // Initial inputs
    // Text from VScode of active file after sanitization
    analysisTarget?: string;

    
    // Pipeline outputs
    parsed?: BlockEvent[];

    // Prompt generated by PromptBuilder to send to Ollama
    prompt?: ChatMessage[];

    // Response from Ollama
    modelResponse?: string;

    //Parsed and structured output from the model
    analysisResult?: ModelAnalysisResult;

    // Cursor line (0-based) at the time analysis was triggered
    cursorLine?: number;

    // compiler error/warnings
    diagnostics?: vscode.Diagnostic[];

    constructor(doc: vscode.TextDocument);

    /** TEST ONLY: construct from raw text for unit tests */
    constructor(text: string);
    constructor(docOrText: vscode.TextDocument | string) {
        if (typeof docOrText === 'string') {
            this.text = docOrText;
        } else {
            this.snapshot = snapshot(docOrText);
        }
    }
}
