import * as vscode from 'vscode';
import { FileSnapshot, snapshot } from '../core/FileSnapshot';
import { throws } from 'assert';

export class ElevateContext {
    // File snapshot with version numbers and full text before analysis
    readonly snapshot?: FileSnapshot;

    // For testing
    text?: string;

    // Initial inputs
    // Text from VScode of active file after sanitization
    analysisTarget?: string;

    
    // Pipeline outputs
    // File after being parsed
    //parsed?: ParsedFile;

    // Prompt generated by PromptBuilder to sender to Ollama
    // prompt?: Prompt obj;

    // Response from Ollama
    // modelResponse?: Response obj;

    // compiler error/warnings
    diagnostics?: vscode.Diagnostic[];

    constructor(doc: vscode.TextDocument);

    /** TEST ONLY: construct from raw text for unit tests */
    constructor(text: string);
    constructor(docOrText: vscode.TextDocument | string) {
        if (typeof docOrText === 'string') {
            this.text = docOrText;
        } else {
            this.snapshot = snapshot(docOrText);
        }
    }
}
